### ISSUE TITLE
Writing custom data to the default collection

### ISSUE THREAD

**Issue by gjvpaet** [mongodb-js/connect-mongodb-session#54]
Hi, is there a way to write custom data to the default collection like for example the details of the user?

**Comment by zyumbik** [comment]
As far as I know, there is not. You have to create the one that stores other data manually.

**Comment by ksuhiyp** [comment]
Hi @vkarpov15,

Did any of you guys managed to solve max number of concurrent login sessions using session store collection?

@gjvpaet  request is convenient, for instance we can tell session collection that specific session is active (loggedIn) -in order to prevent any other login attempt from other clients, doesn't this make sense much more than adding that field somewhere outside session collection?

**Comment by vkarpov15** [comment]
@ksuhiyp what max number of concurrent login sessions? I'm not aware of such a limit
